server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: service-provider2
  datasource:
    username: root
    password: haha
    url: jdbc:mysql://localhost:3306/quiz_system
    driver-class-name: com.mysql.cj.jdbc.Driver

##  authentication: config username, password in yml file
#  security:
#    user:
#      name: shawn
#      password: shawn