server:
  port: 8089
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: batch-server
  datasource:
    username: root
    password: WOSH
    url: jdbc:mysql://localhost:3306/pokedex
    driver-class-name: com.mysql.cj.jdbc.Driver
    # SQL to initialize schema by spring batch
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
  batch:
    initialize-schema: always
    job:
      names: parent job 5,listener job,reader job # specify the target job to launce
