server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: service-provider2

##  authentication: config username, password in yml file
#  security:
#    user:
#      name: shawn
#      password: shawn